### ISSUE TITLE
BLE-Mouse has a dependency on Keyboard

### ISSUE THREAD

**Issue by consciouspnm** [T-vK/ESP32-BLE-Mouse#10]
BLEMouse.cpp has ` bleKeyboardInstance->onStarted(pServer);` at line 164, so won't compile and link without commenting it out.

**Comment by T-vK** [comment]
Instead of commenting the line out it should be changed to `bleMouseInstance->onStarted(pServer);`.
It's difficult for me to maintain these projects as I'm working on at least 20 other projects simultaneously. 
If you want to help you could test it and make a Pull Request. I'd gladly accept it.

**Comment by T-vK** [comment]
This has been fixed in #11.
