### ISSUE TITLE
Keep mouse cursor at screen center

### ISSUE THREAD

**Issue by dc59** [T-vK/ESP32-BLE-Mouse#13]
Thanks for your great project!

I connected esp32 to an android phone, how can I move mouse cursor to the center of screen whatever the mouse had been moved to any position.

**Comment by T-vK** [comment]
Check https://forum.arduino.cc/index.php?topic=679510.0

**Comment by dc59** [comment]
Thanks for your help!

**Comment by zuozhehao** [comment]
> Thanks for your help!

@dc59 Hello, have you solved the problem？

**Comment by zuozhehao** [comment]
@dc59 Hello, has your problem been solved? I have encountered similar problems

**Comment by dc59** [comment]
No, I didn't solve this problem yet.
