### ISSUE TITLE
does it work in ipadOS ?

### ISSUE THREAD

**Issue by rogerjin1206** [T-vK/ESP32-BLE-Mouse#33]
sorry this is not a issue..

I am curious it,

does it work in ipadOS ?

I read it 

 Customize Bluetooth device name/manufacturer
 Compatible with Android
 Compatible with Windows
 Compatible with Linux
 Compatible with MacOS X (not stable, some people have issues, doesn't work with old devices)
 Compatible with iOS (not stable, some people have issues, doesn't work with old devices)

Only Ipad was excluded from the list.

**Comment by T-vK** [comment]
#20

**Comment by rogerjin1206** [comment]
> #20

thank you !
