### ISSUE TITLE
Feature request: drag and drop (mouse-down, move and mouse-up)

### ISSUE THREAD

**Issue by elshnkhll** [T-vK/ESP32-BLE-Mouse#48]
Feature request: drag and drop (mouse-down, move and mouse-up). If this feature is possible to achieve with current version, then please add an example. Thanks.

**Comment by fish1968** [comment]
I think that is possible because what you want to do is just 
1. press left key without releasing 
2. move the cursor around
3. release the left key
Hope it would help.

Thanks.

**Comment by elshnkhll** [comment]
Thanks.

**Comment by hitokirihahn** [comment]
how to achieve press left key without releasing?
