### ISSUE TITLE
Got an error with "BleMouse.cpp"

### ISSUE THREAD

**Issue by AiueoABC** [T-vK/ESP32-BLE-Mouse#9]
I got an error when I try to write examples on Arduino.

I fixed this with rewriting ln164 in "BleMouse.cpp"
from
bleKeyboardInstance->onStarted(pServer);
to
bleMouseInstance->onStarted(pServer);

**Comment by T-vK** [comment]
Thanks for reporting. Yes, this needs to be fixed.

**Comment by T-vK** [comment]
Should be fixed now, thanks to ricalvrod.
